/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "../headers/parser.h"
#include <stdio.h>
#include <string.h>

int main() {
  char c[255];
  float f;
  Parser *parser;
  while (true) {
    printf("lisp> ");
    fgets(c, 255, stdin);
    if (strcmp(c, "exit\n") == 0) {
      break;
    }
    try {
      parser = new Parser(c);
      f = parser->parse();
      printf("%f\n", f);
    } catch (Exception &e) {
      printf("ERROR: %s\n", e.message);
    }
  }
  return 0;
}
