/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "../headers/parser.h"
#include <stdio.h>
#include <string.h>

int main(int argc, char *argv[]) {

  FILE *stream = stdin;
  if (argc > 1) {
    char *filepath = argv[1];
    stream = fopen(filepath, "r");

    if (stream == 0) {
      printf("does not possible open file %s\n", filepath);
      return 0;
    }
  }
  float f;

  Parser *parser;
  printf("lisp> ");
  try {
    parser = new Parser(stream);
    f = parser->parse();
    printf("%f\n", f);
  } catch (Exception &e) {
    printf("ERROR: %s\n", e.message);
  }
  return 0;
}
